import MainLayout from "@/components/templates/layouts/MainLayout";
import "@styles/globals.css";
import { Roboto } from "next/font/google";

const inter = Roboto({
  weight: "400",
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " dark bg-black text-white selection:bg-pink-600"
        }
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
